---
oauth_url_template: "https://slack.com/oauth/authorize{?query*}"
api_url_template: "https://slack.com/api/{command}"
client_id: YOUR_CLIENT_ID
client_secret: YOUR_CLIENT_SECRET
verification_token: YOUR_VERIFICATION_TOKEN
scopes:
- incoming-webhook
- commands
- chat:write:user
- chat:write:bot
- users:read
